export const ADD_VEHICLES = "ADD_VEHICLES";
export const SORT_VEHICLE_LIST = "SORT_VEHICLE_LIST";
export const FILTER_LIST_BY_STRING = "FILTER_LIST_BY_STRING";
export const SET_ACTIVE_VEHICLE = "SET_ACTIVE_VEHICLE";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
